CUDA_VISIBLE_DEVICES='1' python test.py \
--content_path datasets/c_14 \
--style_path datasets/abacus \
--name AdaAttN \
--model adaattn \
--dataset_mode unaligned \
--load_size 512 \
--crop_size 512 \
--image_encoder_path checkpoints/vgg_normalised.pth \
--gpu_ids 0 \
--skip_connection_3 \
--shallow_layer
